POST https://sample-node-login-app-deploy.onrender.com/users
Content-Type: application/json

{   
    "name":"phanim murari",
    "username":"phani",
    "password": "phani123",
    "gender": "Male",
    "location":"hyderabad"
}s