### Registering a User

POST http://localhost:3001/users
Content-Type: application/json

{   
    "name":"phani m",
    "username":"phani m",
    "password": "phani123456",
    "gender": "Male",
    "location":"hyderabad"
}


### User Login


POST http://localhost:3001/login
Content-Type: application/json

{   
    "username":"phani m",
    "password": "phani123456"
}
